language: python
sudo: false
git:
  depth: 1
cache:
- pip: true
addons:
  apt:
    packages:
    - swig
    - libxml2-dev
    - libglpk-dev
    - glpk-utils
branches:
  only:
  - master
  - develop
  - /v\d+\.\d+\.\d+/
matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: TOXENV=flake8
  - python: 3.5
    env: TOXENV=docs
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5-dev
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
before_install:
- travis_retry pip install -U pip setuptools wheel tox
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    repo: opencobra/memote
    python: '3.6'
    tags: true
  user:
    secure: MM0+CQ7jYF3TmWM15UfjJANGb1rRLY+GjEro4G/8teSOxyGxR+PzWeViJn86TJsDD+AaYy7/mvq5lF7QN5q4tcxmr9uVVH9iOzZk/HcT0raD3Lk1GcS0h6N6LxG3sz1XqOOa224hp9VK1U/9ryvaiOzZo4KAh/h1uz0QafNWNPCBZ3CfRV1dCw7NI7TAthpCy8mTMYUZko/uGo86wwT1ks005yOeefuG3zqwvJCRnhpqR2Ky+/GwnxW9it+uVOpc7cHPOOQkNxbA1veLzvfaGdg2x3ceRi0kvRfHhKVudwwzxXWfz/HScEmNYLglkwvf/E34N+JfBxpVkjtvFRDopvTbHb98ctJflKvv1I4UnBZSP9sLiJ012OC+4q9YNy78MFrGQhoSC+aTi9K+teLFMxvoiVvlDattjuvXOAxpxaamJd6eLdj3AfpGqOCB0r6X8ixi1/UcCFjTt8oRyFofb5P5tkUGdWjGjRyh9OqQidpNpM5qyOnaQ7Vz4JuPrRl5/LSThdSvRWV8Q3JBUhf383nHc1z+uCZ4T4uLBmfMcKvZErAOEDuJeB/g8vLvG28SfyUTfGTvFeEVm8E7bCpQWodZ8FKxau+6BZru01kDtASQzPgwdnfUOPPtNVwRW8NMc+X18VNckTf6GVoXbvHu61c+kq6CkOqSOIhHOa+fWWM=
  password:
    secure: fwQqiOalEDnYyeTw8bAg/Vx+FbjQHocEEQN/L+ZGWUtPhhO7vantkLditi6JjVxXBxNkIpAmD5datZ6QDj5gxJoE0y3ef/ZTCv8Y1GorHyHKOAsoY7a/m5LbW6CGPciRz375+HMePLmU88nbLNS4Fbi6wHmM5mZ9QXSyWJjc6gZwxlc9UZj96rnrsQoSE1j7NL7BrTaWrRQHexUf7qA77ruKbOhwqpydrYDlc4fw/UjdmDdELV2nRV9/oUVc2AAI9IurVNAO8s0e6SyQoEM3r3cI+ougFOO0O2ydnnBXGZPv8H2LbypS5olvbfgsBjGXgt7AEKkWxhEC2CT7z45xuU4mhxWeU9Is0I4JQlNXSwmxjkWAoYQU12N7gi1fET/JaXUJzCIX+sTKmJ4Lg576F5NvvVZUkRumnUEBJpexQKlD6VNDalmnFzRVfhYf0snrx8SHE6LLwFKbketuFzb70lVTxbrIXuulj1l7Jjy8H7VQ0TRUV0MminbbhctWgKnBVVi3tee+77FslWaJfrKede5av/KrykCl9ssP8ASKvUjXjkV5M8lPXMjhVNLZDrge8SFnz/2wmoPkczZrJWn3fD+w5yJBW6IFt3ZpX6M1V48B3aG0TcEmJ3KjR8+lWeSSF3IVxhQoDPM3P/PmB25iBS38P8C0w0vcTx7JFJVQuak=
notifications:
  slack:
    secure: udevSzdcN71zqk9Y8Rev5zrf7gjHWdLQPMbz30YXrUD3uK2i4ofvXIKJhwctchFfqjxNQlm57QOb3YDksaiizHGskx7ljnEGPrrDoVBnTG7wI/wcw6JcTDOII9klA+sp/yMKniuBYHML5U7xiEuNpMblgnUg1P/q9qcoNDIgli1uS6ftzuq242kMDcPxf+L4XOvK8SLukfVUjAKqLJoywPvJ6hqcJPbfIRRBpCGSMRpbPbkoju7aFt7Maz4VY5CpKqPRNodldxyzn3ZvPQvdAPX0o5UW3ioF7b5/CCbPJNhREQvzWdAJlJP9tZYXkTBrGDrFNEEjaCHhUbkCVL5BhndGz4W+guWCXx+gOhQ/imdqVlfXYOnl9/StquhHF7Uc3aYJZ1uzHW1WAm1cyfYjemiORawVgswv1jPtxB4Fa474DPOMCIX6qGeck0CuS/gGn+NlitWdypggTK8PyN+SCH+vS/brJ/+OPpr5lj1UHd9qeI4O8OntZbxZgJH8saCzULVh/FszSusLJ61djlX6tn2fCvNnOxR1FdhaPvR3srKxhAOH2RpLm3kTVFAHf5a28umIRNK79M7KZUEbap+7GlH2dCtb23pVToUngdGc6paZ/RDe8qeZbG4obLbRCnX/VvWNlgHlYo5SMr3vhawmf/ErJDWQbc5ZuhhVRm3L/4g=
