language: python
sudo: false
git:
  depth: 1
cache:
  - pip: true
addons:
  apt:
    packages:
      - swig
      - libxml2-dev
      - libglpk-dev
      - glpk-utils

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=flake8

before_install:
  - pip install -U pip setuptools wheel
install: pip install -U tox
script: travis_wait tox -e ${TOXENV}

after_success:
  - if [ "${TOXENV}" != "flake8" ]; then codecov; fi

#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: midnighter
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: biosustain/memote
#    condition: $TOXENV == py27
